apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: busybox
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/output
  - name: nose-tests
    image: python:3.9
    script: |
      #!/bin/sh
      echo "Running Nose Tests..."
      pip install nose
      nosetests tests
